---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alufletes/aluminiologo.oo.gd/formaciones
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp iadmin.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp detalle.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp login.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp api.php $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp script_new.js $DEPLOYPATH
